# Generated by Django 4.1.1 on 2022-10-01 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='user name')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=4, verbose_name='trade type')),
                ('symbol', models.CharField(max_length=4, verbose_name='the stock symbol')),
                ('price', models.FloatField(verbose_name='stock price')),
                ('timestamp', models.DateTimeField(verbose_name='transaction time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_platform.user')),
            ],
        ),
    ]
